# Generated by Django 2.0.4 on 2018-05-05 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('main_classic', models.BooleanField(default=False)),
                ('main_blowJob_w_condom', models.BooleanField(default=False)),
                ('main_cunni', models.BooleanField(default=False)),
                ('main_group_sex', models.BooleanField(default=False)),
                ('main_lesbi_lesbi', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
