# Generated by Django 2.0.4 on 2018-05-05 16:36

import Bish_vip.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='choiseBodyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='-', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='choiseEyeColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='-', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='choiseRaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='-', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='choises_hair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='-', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=15)),
                ('height', models.CharField(blank=True, max_length=10)),
                ('grud', models.CharField(blank=True, max_length=10)),
                ('WorkDestrict', models.CharField(max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=10)),
                ('Description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('image_1', models.FileField(upload_to=Bish_vip.models.upload_location)),
                ('image_2', models.FileField(blank=True, upload_to=Bish_vip.models.upload_location)),
                ('image_3', models.FileField(blank=True, upload_to=Bish_vip.models.upload_location)),
                ('image_4', models.FileField(blank=True, upload_to=Bish_vip.models.upload_location)),
                ('image_5', models.FileField(blank=True, upload_to=Bish_vip.models.upload_location)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('appart_1', models.CharField(blank=True, default='-', max_length=10)),
                ('appart_2', models.CharField(blank=True, default='-', max_length=10)),
                ('appart_naigth', models.CharField(blank=True, default='-', max_length=10)),
                ('outside_1', models.CharField(blank=True, default='-', max_length=10)),
                ('outside_2', models.CharField(blank=True, default='-', max_length=10)),
                ('outside_nigth', models.CharField(blank=True, default='-', max_length=10)),
                ('main_classic', models.BooleanField(default=True)),
                ('main_blowJob_w_condom', models.BooleanField(default=True)),
                ('main_cunni', models.BooleanField(default=True)),
                ('main_group_sex', models.BooleanField(default=True)),
                ('main_lesbi_lesbi', models.BooleanField(default=True)),
                ('mbr', models.BooleanField(default=True)),
                ('mbr_price', models.TextField(blank=True, max_length=10, null=True)),
                ('anal_sex', models.BooleanField(default=False)),
                ('anal_sex_price', models.TextField(blank=True, max_length=10, null=True)),
                ('dop_end_mouth', models.BooleanField(default=True)),
                ('dop_end_face', models.BooleanField(default=True)),
                ('dop_glub_minet', models.BooleanField(default=True)),
                ('dop_toys', models.BooleanField(default=True)),
                ('dop_role_game', models.BooleanField(default=True)),
                ('dop_couple_service', models.BooleanField(default=True)),
                ('dop_video', models.BooleanField(default=True)),
                ('dop_company', models.BooleanField(default=True)),
                ('massage_relax', models.BooleanField(default=True)),
                ('massage_classic', models.BooleanField(default=True)),
                ('massage_profi', models.BooleanField(default=True)),
                ('massage_tiski', models.BooleanField(default=True)),
                ('massage_prostat', models.BooleanField(default=True)),
                ('massage_erotic', models.BooleanField(default=True)),
                ('massage_sakura', models.BooleanField(default=True)),
                ('dance_profi', models.BooleanField(default=True)),
                ('dance_NoProfi', models.BooleanField(default=True)),
                ('dance_lesbi_show', models.BooleanField(default=True)),
                ('dance_lisbi', models.BooleanField(default=True)),
                ('sado_bandaj', models.BooleanField(default=True)),
                ('sado_gospoja', models.BooleanField(default=True)),
                ('sado_rabyn', models.BooleanField(default=True)),
                ('sado_dominant', models.BooleanField(default=True)),
                ('sado_porka', models.BooleanField(default=True)),
                ('sado_fetish', models.BooleanField(default=True)),
                ('sado_trampling', models.BooleanField(default=True)),
                ('extrim_anilingus', models.BooleanField(default=True)),
                ('extrim_dojd_out', models.BooleanField(default=True)),
                ('extrim_dojd_in', models.BooleanField(default=True)),
                ('extrim_strapon', models.BooleanField(default=True)),
                ('extrim_fisting_anal', models.BooleanField(default=True)),
                ('extrim_fisting_vagin', models.BooleanField(default=True)),
                ('BodyType', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Bish_vip.choiseBodyType')),
                ('RaceType', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bish_vip.choiseRaceType')),
                ('eyeColor', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Bish_vip.choiseEyeColor')),
                ('hair', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Bish_vip.choises_hair')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
