# Generated by Django 2.0.4 on 2018-05-06 08:08

import Bish_vip.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bish_vip', '0003_auto_20180506_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_1',
            field=models.FileField(blank=True, upload_to=Bish_vip.models.upload_location),
        ),
    ]
