# Generated by Django 2.0.4 on 2018-05-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bish_vip', '0004_auto_20180506_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_1',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
